/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณEICLO100_RDMบAutor  ณEletromega        บ Data ณ  12/10/10   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ Rotina de Manuten็ao de FFC                                บฑฑ
ฑฑบ          ณ Travar os acesso dos usuarios                              บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP10                                                       บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
#INCLUDE "PROTHEUS.CH"

User Function EICLO100() 
Local lRet 		:= .T.
Local cParam 	:= PARAMIXB 

If !(U_IsAdm() .Or. U_InGroup(GetMV("FS_GPEICPA")))  

	If ValType(ParamIXB) == "C"
 		cParam := ParamIXB  
	EndIf

	Do Case
		Case cParam == "ATUALIZA"    
    		nOpca := IIf(nOpca == 4,0,nOpca)  // Inibir a estorno/exclusao do FFC //
    		ApMsgStop('Opera็ao nao permitida!','ATENวรO') 
		Case cParam == "VAL_SCPE2"   
    		//ApMsgStop(cParam,'ATENวรO')
    		//ApMsgStop(Str(nOpca,2),'ATENวรO') 
    		//lRet  := .F.
    		//ApMsgStop('Opera็ao nao permitida!','ATENวรO')					
    EndCase 

EndIf
Return(lRet)